#!/usr/bin/env node
// Regenerates src/routes.generated.ts — a static import registry of every
// `src/app/api/**/route.ts` handler, mounted by the Hono server (src/server.ts).
// Usage: node scripts/generate-routes.mjs
import { readdirSync, writeFileSync, existsSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const apiDir = join(root, "src", "app", "api");

function walkRoutes(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const st = statSync(full);
    if (st.isDirectory()) {
      out.push(...walkRoutes(full));
    } else if (entry === "route.ts") {
      out.push(full);
    }
  }
  return out;
}

function routeEntries() {
  const files = walkRoutes(apiDir);
  const out = [];
  for (const file of files) {
    const rel = relative(join(root, "src"), file) // app/api/.../route.ts
      .split(sep)
      .join("/");
    if (!rel.startsWith("app/api/") || !rel.endsWith("/route.ts")) continue;
    // Import specifier keeps the trailing `/route` (resolves to route.ts).
    const importSpecifier = `@/${rel.replace(/\.ts$/, "")}`;
    // Mount path: `/api/...` with Next.js [x] segments converted to Hono :x.
    const mountSegs = rel
      .replace(/^app\/api\//, "")
      .replace(/\/route\.ts$/, "")
      .split("/")
      .map((seg) => (seg.startsWith("[") && seg.endsWith("]") ? `:${seg.slice(1, -1)}` : seg));
    out.push({ importSpecifier, mountPath: `/api/${mountSegs.join("/")}` });
  }
  // Lexical sort of the full rel path (dirs + `route` suffix) reproduces the
  // canonical ordering — e.g. `reviews/[id]/resolve/route` < `reviews/route`.
  return out.sort((a, b) => (a.importSpecifier < b.importSpecifier ? -1 : a.importSpecifier > b.importSpecifier ? 1 : 0));
}

const entries = routeEntries();
const lines = [];
lines.push("// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.");
lines.push("// Statically imports every route handler so tsup bundles them all.");
lines.push("");
entries.forEach((entry, i) => {
  lines.push(`import * as m${i} from "${entry.importSpecifier}";`);
});
lines.push("");
lines.push("export const ROUTES: Array<{ path: string; mod: Record<string, unknown> }> = [");
entries.forEach((entry, i) => {
  lines.push(`  { path: "${entry.mountPath}", mod: m${i} as unknown as Record<string, unknown> },`);
});
lines.push("];");
lines.push("");

const outPath = join(root, "src", "routes.generated.ts");
writeFileSync(outPath, lines.join("\n"));
console.log(`[generate-routes] wrote ${entries.length} routes -> ${relative(root, outPath)}`);