// AUTO-GENERATED by scripts/generate-routes.mjs — do not edit by hand.
// Statically imports every route handler so tsup bundles them all.

import * as m0 from "@/app/api/admin/dashboard/route";
import * as m1 from "@/app/api/admin/data/route";
import * as m2 from "@/app/api/admin/evidence/route";
import * as m3 from "@/app/api/admin/ingredients/route";
import * as m4 from "@/app/api/admin/product-image/route";
import * as m5 from "@/app/api/admin/products/route";
import * as m6 from "@/app/api/admin/reviews/[id]/resolve/route";
import * as m7 from "@/app/api/admin/reviews/route";
import * as m8 from "@/app/api/admin/users/route";
import * as m9 from "@/app/api/analysis/personalized/route";
import * as m10 from "@/app/api/analyze/route";
import * as m11 from "@/app/api/auth/guest/route";
import * as m12 from "@/app/api/auth/login/route";
import * as m13 from "@/app/api/auth/me/route";
import * as m14 from "@/app/api/auth/signup/route";
import * as m15 from "@/app/api/chat/route";
import * as m16 from "@/app/api/docs/route";
import * as m17 from "@/app/api/evidence/[barcode]/route";
import * as m18 from "@/app/api/external/fda/drug-events/route";
import * as m19 from "@/app/api/external/fda/drug-labels/route";
import * as m20 from "@/app/api/external/fda/food-enforcement/route";
import * as m21 from "@/app/api/external/openfoodfacts/product/[barcode]/route";
import * as m22 from "@/app/api/external/pubchem/compound/route";
import * as m23 from "@/app/api/external/pubchem/properties/route";
import * as m24 from "@/app/api/external/usda/search/route";
import * as m25 from "@/app/api/external/who/indicators/route";
import * as m26 from "@/app/api/food-safety-assistant/route";
import * as m27 from "@/app/api/history/[id]/route";
import * as m28 from "@/app/api/history/route";
import * as m29 from "@/app/api/ingredients/[id]/route";
import * as m30 from "@/app/api/ingredients/analyze/route";
import * as m31 from "@/app/api/nutrition/[barcode]/route";
import * as m32 from "@/app/api/product-images/[barcode]/route";
import * as m33 from "@/app/api/products/[id]/alternatives/feedback/route";
import * as m34 from "@/app/api/products/[id]/alternatives/route";
import * as m35 from "@/app/api/products/barcode/[barcode]/route";
import * as m36 from "@/app/api/products/compare/route";
import * as m37 from "@/app/api/products/route";
import * as m38 from "@/app/api/products/search/route";
import * as m39 from "@/app/api/regulatory/analyze/route";
import * as m40 from "@/app/api/scan/label/route";
import * as m41 from "@/app/api/temp/[id]/route";
import * as m42 from "@/app/api/users/me/preferences/route";
import * as m43 from "@/app/api/users/me/route";

export const ROUTES: Array<{ path: string; mod: Record<string, unknown> }> = [
  { path: "/api/admin/dashboard", mod: m0 as unknown as Record<string, unknown> },
  { path: "/api/admin/data", mod: m1 as unknown as Record<string, unknown> },
  { path: "/api/admin/evidence", mod: m2 as unknown as Record<string, unknown> },
  { path: "/api/admin/ingredients", mod: m3 as unknown as Record<string, unknown> },
  { path: "/api/admin/product-image", mod: m4 as unknown as Record<string, unknown> },
  { path: "/api/admin/products", mod: m5 as unknown as Record<string, unknown> },
  { path: "/api/admin/reviews/:id/resolve", mod: m6 as unknown as Record<string, unknown> },
  { path: "/api/admin/reviews", mod: m7 as unknown as Record<string, unknown> },
  { path: "/api/admin/users", mod: m8 as unknown as Record<string, unknown> },
  { path: "/api/analysis/personalized", mod: m9 as unknown as Record<string, unknown> },
  { path: "/api/analyze", mod: m10 as unknown as Record<string, unknown> },
  { path: "/api/auth/guest", mod: m11 as unknown as Record<string, unknown> },
  { path: "/api/auth/login", mod: m12 as unknown as Record<string, unknown> },
  { path: "/api/auth/me", mod: m13 as unknown as Record<string, unknown> },
  { path: "/api/auth/signup", mod: m14 as unknown as Record<string, unknown> },
  { path: "/api/chat", mod: m15 as unknown as Record<string, unknown> },
  { path: "/api/docs", mod: m16 as unknown as Record<string, unknown> },
  { path: "/api/evidence/:barcode", mod: m17 as unknown as Record<string, unknown> },
  { path: "/api/external/fda/drug-events", mod: m18 as unknown as Record<string, unknown> },
  { path: "/api/external/fda/drug-labels", mod: m19 as unknown as Record<string, unknown> },
  { path: "/api/external/fda/food-enforcement", mod: m20 as unknown as Record<string, unknown> },
  { path: "/api/external/openfoodfacts/product/:barcode", mod: m21 as unknown as Record<string, unknown> },
  { path: "/api/external/pubchem/compound", mod: m22 as unknown as Record<string, unknown> },
  { path: "/api/external/pubchem/properties", mod: m23 as unknown as Record<string, unknown> },
  { path: "/api/external/usda/search", mod: m24 as unknown as Record<string, unknown> },
  { path: "/api/external/who/indicators", mod: m25 as unknown as Record<string, unknown> },
  { path: "/api/food-safety-assistant", mod: m26 as unknown as Record<string, unknown> },
  { path: "/api/history/:id", mod: m27 as unknown as Record<string, unknown> },
  { path: "/api/history", mod: m28 as unknown as Record<string, unknown> },
  { path: "/api/ingredients/:id", mod: m29 as unknown as Record<string, unknown> },
  { path: "/api/ingredients/analyze", mod: m30 as unknown as Record<string, unknown> },
  { path: "/api/nutrition/:barcode", mod: m31 as unknown as Record<string, unknown> },
  { path: "/api/product-images/:barcode", mod: m32 as unknown as Record<string, unknown> },
  { path: "/api/products/:id/alternatives/feedback", mod: m33 as unknown as Record<string, unknown> },
  { path: "/api/products/:id/alternatives", mod: m34 as unknown as Record<string, unknown> },
  { path: "/api/products/barcode/:barcode", mod: m35 as unknown as Record<string, unknown> },
  { path: "/api/products/compare", mod: m36 as unknown as Record<string, unknown> },
  { path: "/api/products", mod: m37 as unknown as Record<string, unknown> },
  { path: "/api/products/search", mod: m38 as unknown as Record<string, unknown> },
  { path: "/api/regulatory/analyze", mod: m39 as unknown as Record<string, unknown> },
  { path: "/api/scan/label", mod: m40 as unknown as Record<string, unknown> },
  { path: "/api/temp/:id", mod: m41 as unknown as Record<string, unknown> },
  { path: "/api/users/me/preferences", mod: m42 as unknown as Record<string, unknown> },
  { path: "/api/users/me", mod: m43 as unknown as Record<string, unknown> },
];
